spring.application.name=zavrsni

spring.web.cors.allowed-origins=http://localhost:3000
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.web.cors.allow-credentials=true

# JDBC URL za PostgreSQL
# Driver
spring.datasource.driver-class-name=${DB_DRIVER:org.postgresql.Driver}


spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


server.servlet.session.cookie.same-site=NONE
server.servlet.session.cookie.secure=true

server.port=8081